version: '3.8'

services:
  kafka:
    container_name: kafka-t2
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.102:9092

  mongodb:
    container_name: turkcell2-filterdb-dev
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "turkcell"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
    volumes:
      - mongodb_data:/data/db/
volumes:
  kafka_data:
  mongodb_data: